import 'package:flutter/material.dart';
import 'dart:convert';
import 'package:mobility_sqr/Constants/AppConstants.dart';
import 'package:mobility_sqr/ModelClasses/Approval.dart';
import 'package:sizer/sizer.dart';


class ApprovalsScreen extends StatefulWidget {
  @override
  _ApprovalsScreenState createState() => _ApprovalsScreenState();
}

class _ApprovalsScreenState extends State<ApprovalsScreen> {
  var checkedValue = false;
  String approvalList = """
{
    "massage": "data found",
    "status": true,
    "data": [
        {
            "id": 501,
            "date_created": "2021-01-19T12:22:58.284438+05:30",
            "date_modified": "2021-01-19T12:22:58.284447+05:30",
            "created_by": "Emp112",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR122601",
            "project_name": "3M Lights on support",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": "testing",
            "home_contact_name": "Himanshu",
            "home_phone_ext": "+91",
            "home_phone_number": "8505957287",
            "is_laptop_required": true,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "Emp0009",
            "project_manager": "kgp001",
            "business_lead": "Emp0010",
            "client_executive_lead": "Emp0011",
            "have_laptop": true,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "08/01/2021",
            "expence_estimatedCost": "2280",
            "expence_fromCountry": "United States",
            "expence_returnDate": "28/01/2021",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "Emp112",
            "project": "10002",
            "organization": "ORG150866",
            "emp_code": "Emp112",
            "first_name": "Divyanshu",
            "last_name": "Kumar",
            "details": [
                {
                    "id": 483,
                    "travel_req_id_id": "TR122601",
                    "travelling_country": "United States",
                    "travelling_country_to": "United States",
                    "office_location": "100006",
                    "client_number": "8978545145",
                    "organization": null,
                    "source_city": "New York, NY",
                    "destination_city": "Indianapolis, IN",
                    "departure_date": "2021-01-08T06:52:36.397000Z",
                    "return_date": "2021-01-27T18:30:00Z",
                    "is_accmodation_required": true,
                    "accmodation_start_date": "2021-01-08T06:52:36.397Z",
                    "accmodation_end_date": "2021-01-18T18:30:00.000Z",
                    "travel_purpose": "Work",
                    "assignment_type": null,
                    "applicable_visa": "",
                    "visa_number": "",
                    "visa_expiry_date": "",
                    "host_hr_name": "Himanshu",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "8505957287",
                    "is_client_location": true,
                    "client_name": "Steve",
                    "client_address": "Gurgaon",
                    "hotel_cost": 880,
                    "per_diem_cost": 1000,
                    "airfare_cost": null,
                    "transportation_cost": 400,
                    "total_cost": 2280,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": true
                }
            ],
            "dependent": [
                {
                    "id": 320,
                    "date_created": "2021-01-19T12:23:00.827561+05:30",
                    "date_modified": "2021-01-19T12:23:00.827569+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "SP",
                    "dependent_name": "test9",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR122601",
                    "organization": null
                },
                {
                    "id": 321,
                    "date_created": "2021-01-19T12:23:00.847647+05:30",
                    "date_modified": "2021-01-19T12:23:00.847655+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "PR",
                    "dependent_name": "p1",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR122601",
                    "organization": null
                },
                {
                    "id": 322,
                    "date_created": "2021-01-19T12:23:00.866354+05:30",
                    "date_modified": "2021-01-19T12:23:00.866363+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "Ot",
                    "dependent_name": "test2",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR122601",
                    "organization": null
                }
            ]
        },
        {
            "id": 500,
            "date_created": "2021-01-18T18:38:17.239919+05:30",
            "date_modified": "2021-01-18T18:38:17.239928+05:30",
            "created_by": "Emp112",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR249142",
            "project_name": "3M Lights on support",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": "testing",
            "home_contact_name": "Himanshu",
            "home_phone_ext": "+91",
            "home_phone_number": "8505957287",
            "is_laptop_required": true,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "Emp0009",
            "project_manager": "kgp001",
            "business_lead": "Emp0010",
            "client_executive_lead": "Emp0011",
            "have_laptop": true,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "08/01/2021",
            "expence_estimatedCost": "2280",
            "expence_fromCountry": "United States",
            "expence_returnDate": "28/01/2021",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "Emp112",
            "project": "10002",
            "organization": "ORG150866",
            "emp_code": "Emp112",
            "first_name": "Divyanshu",
            "last_name": "Kumar",
            "details": [
                {
                    "id": 482,
                    "travel_req_id_id": "TR249142",
                    "travelling_country": "United States",
                    "travelling_country_to": "United States",
                    "office_location": "100006",
                    "client_number": "8978545145",
                    "organization": null,
                    "source_city": "New York, NY",
                    "destination_city": "Indianapolis, IN",
                    "departure_date": "2021-01-08T06:52:36.397000Z",
                    "return_date": "2021-01-27T18:30:00Z",
                    "is_accmodation_required": true,
                    "accmodation_start_date": "2021-01-08T06:52:36.397Z",
                    "accmodation_end_date": "2021-01-18T18:30:00.000Z",
                    "travel_purpose": "Work",
                    "assignment_type": null,
                    "applicable_visa": "",
                    "visa_number": "",
                    "visa_expiry_date": "",
                    "host_hr_name": "Himanshu",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "8505957287",
                    "is_client_location": true,
                    "client_name": "Steve",
                    "client_address": "Gurgaon",
                    "hotel_cost": 880,
                    "per_diem_cost": 1000,
                    "airfare_cost": null,
                    "transportation_cost": 400,
                    "total_cost": 2280,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": true
                }
            ],
            "dependent": [
                {
                    "id": 317,
                    "date_created": "2021-01-18T18:38:20.256399+05:30",
                    "date_modified": "2021-01-18T18:38:20.256408+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "SP",
                    "dependent_name": "test9",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR249142",
                    "organization": null
                },
                {
                    "id": 318,
                    "date_created": "2021-01-18T18:38:20.284204+05:30",
                    "date_modified": "2021-01-18T18:38:20.284212+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "PR",
                    "dependent_name": "p1",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR249142",
                    "organization": null
                },
                {
                    "id": 319,
                    "date_created": "2021-01-18T18:38:20.302593+05:30",
                    "date_modified": "2021-01-18T18:38:20.302602+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "Ot",
                    "dependent_name": "test2",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR249142",
                    "organization": null
                }
            ]
        },
        {
            "id": 499,
            "date_created": "2021-01-15T16:25:28.088863+05:30",
            "date_modified": "2021-01-15T16:25:28.088876+05:30",
            "created_by": "Emp112",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR295418",
            "project_name": "3M Lights on support",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": "testing",
            "home_contact_name": "Himanshu",
            "home_phone_ext": "+91",
            "home_phone_number": "8505957287",
            "is_laptop_required": true,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "Emp0009",
            "project_manager": "kgp001",
            "business_lead": "Emp0010",
            "client_executive_lead": "Emp0011",
            "have_laptop": true,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "08/01/2021",
            "expence_estimatedCost": "2280",
            "expence_fromCountry": "United States",
            "expence_returnDate": "28/01/2021",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "Emp112",
            "project": "10002",
            "organization": "ORG150866",
            "emp_code": "Emp112",
            "first_name": "Divyanshu",
            "last_name": "Kumar",
            "details": [
                {
                    "id": 481,
                    "travel_req_id_id": "TR295418",
                    "travelling_country": "United States",
                    "travelling_country_to": "United States",
                    "office_location": "100006",
                    "client_number": "8978545145",
                    "organization": null,
                    "source_city": "New York, NY",
                    "destination_city": "Indianapolis, IN",
                    "departure_date": "2021-01-08T06:52:36.397000Z",
                    "return_date": "2021-01-27T18:30:00Z",
                    "is_accmodation_required": true,
                    "accmodation_start_date": "2021-01-08T06:52:36.397Z",
                    "accmodation_end_date": "2021-01-18T18:30:00.000Z",
                    "travel_purpose": "Work",
                    "assignment_type": null,
                    "applicable_visa": "",
                    "visa_number": "",
                    "visa_expiry_date": "",
                    "host_hr_name": "Himanshu",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "8505957287",
                    "is_client_location": true,
                    "client_name": "Steve",
                    "client_address": "Gurgaon",
                    "hotel_cost": 880,
                    "per_diem_cost": 1000,
                    "airfare_cost": null,
                    "transportation_cost": 400,
                    "total_cost": 2280,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": true
                }
            ],
            "dependent": [
                {
                    "id": 314,
                    "date_created": "2021-01-15T16:25:30.223540+05:30",
                    "date_modified": "2021-01-15T16:25:30.223549+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "SP",
                    "dependent_name": "test9",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR295418",
                    "organization": null
                },
                {
                    "id": 315,
                    "date_created": "2021-01-15T16:25:30.244732+05:30",
                    "date_modified": "2021-01-15T16:25:30.244740+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "PR",
                    "dependent_name": "p1",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR295418",
                    "organization": null
                },
                {
                    "id": 316,
                    "date_created": "2021-01-15T16:25:30.273885+05:30",
                    "date_modified": "2021-01-15T16:25:30.273896+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "Ot",
                    "dependent_name": "test2",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR295418",
                    "organization": null
                }
            ]
        },
        {
            "id": 498,
            "date_created": "2021-01-15T16:25:07.898296+05:30",
            "date_modified": "2021-01-15T16:25:07.898305+05:30",
            "created_by": "Emp112",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR170631",
            "project_name": "3M Lights on support",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": "testing",
            "home_contact_name": "Himanshu",
            "home_phone_ext": "+91",
            "home_phone_number": "8505957287",
            "is_laptop_required": true,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "Emp0009",
            "project_manager": "kgp001",
            "business_lead": "Emp0010",
            "client_executive_lead": "Emp0011",
            "have_laptop": true,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "08/01/2021",
            "expence_estimatedCost": "2280",
            "expence_fromCountry": "United States",
            "expence_returnDate": "28/01/2021",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "Emp112",
            "project": "10002",
            "organization": "ORG150866",
            "emp_code": "Emp112",
            "first_name": "Divyanshu",
            "last_name": "Kumar",
            "details": [
                {
                    "id": 480,
                    "travel_req_id_id": "TR170631",
                    "travelling_country": "United States",
                    "travelling_country_to": "United States",
                    "office_location": "100006",
                    "client_number": "8978545145",
                    "organization": null,
                    "source_city": "New York, NY",
                    "destination_city": "Indianapolis, IN",
                    "departure_date": "2021-01-08T06:52:36.397000Z",
                    "return_date": "2021-01-27T18:30:00Z",
                    "is_accmodation_required": true,
                    "accmodation_start_date": "2021-01-08T06:52:36.397Z",
                    "accmodation_end_date": "2021-01-18T18:30:00.000Z",
                    "travel_purpose": "Work",
                    "assignment_type": null,
                    "applicable_visa": "",
                    "visa_number": "",
                    "visa_expiry_date": "",
                    "host_hr_name": "Himanshu",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "8505957287",
                    "is_client_location": true,
                    "client_name": "Steve",
                    "client_address": "Gurgaon",
                    "hotel_cost": 880,
                    "per_diem_cost": 1000,
                    "airfare_cost": null,
                    "transportation_cost": 400,
                    "total_cost": 2280,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": true
                }
            ],
            "dependent": [
                {
                    "id": 311,
                    "date_created": "2021-01-15T16:25:11.110173+05:30",
                    "date_modified": "2021-01-15T16:25:11.110185+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "SP",
                    "dependent_name": "test9",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR170631",
                    "organization": null
                },
                {
                    "id": 312,
                    "date_created": "2021-01-15T16:25:11.343333+05:30",
                    "date_modified": "2021-01-15T16:25:11.343342+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "PR",
                    "dependent_name": "p1",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR170631",
                    "organization": null
                },
                {
                    "id": 313,
                    "date_created": "2021-01-15T16:25:11.464557+05:30",
                    "date_modified": "2021-01-15T16:25:11.464567+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "Ot",
                    "dependent_name": "test2",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR170631",
                    "organization": null
                }
            ]
        },
        {
            "id": 496,
            "date_created": "2021-01-10T09:55:28.828219+05:30",
            "date_modified": "2021-01-10T09:55:28.828230+05:30",
            "created_by": "div944",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR117508",
            "project_name": "TATACOMDEMO",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": null,
            "home_contact_name": "Roy",
            "home_phone_ext": "+91",
            "home_phone_number": "9090909",
            "is_laptop_required": false,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "",
            "project_manager": "",
            "business_lead": "",
            "client_executive_lead": "",
            "have_laptop": false,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "10/01/2021",
            "expence_estimatedCost": "0",
            "expence_fromCountry": "India",
            "expence_returnDate": "03/01/2022",
            "expence_toCountry": "United Kingdom",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "div944",
            "project": "110121",
            "organization": "ORG150866",
            "emp_code": "div944",
            "first_name": "Divyanshu",
            "last_name": "Admin",
            "details": [
                {
                    "id": 478,
                    "travel_req_id_id": "TR117508",
                    "travelling_country": "India",
                    "travelling_country_to": "United Kingdom",
                    "office_location": "100001",
                    "client_number": "",
                    "organization": null,
                    "source_city": "New Delhi",
                    "destination_city": "London",
                    "departure_date": "2021-01-10T04:21:56.987000Z",
                    "return_date": "2022-01-02T18:30:00Z",
                    "is_accmodation_required": false,
                    "accmodation_start_date": "",
                    "accmodation_end_date": "",
                    "travel_purpose": "Work",
                    "assignment_type": null,
                    "applicable_visa": "",
                    "visa_number": "",
                    "visa_expiry_date": "",
                    "host_hr_name": "Steve",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "0909",
                    "is_client_location": false,
                    "client_name": "",
                    "client_address": "",
                    "hotel_cost": 0,
                    "per_diem_cost": 14320,
                    "airfare_cost": 1010,
                    "transportation_cost": 3580,
                    "total_cost": 18910,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": false
                }
            ],
            "dependent": []
        },
        {
            "id": 495,
            "date_created": "2021-01-08T12:58:39.150622+05:30",
            "date_modified": "2021-01-08T12:58:39.150630+05:30",
            "created_by": "div944",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR788994",
            "project_name": "3M Sales Support",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": "test",
            "home_contact_name": "test",
            "home_phone_ext": "+880",
            "home_phone_number": "3452342334242",
            "is_laptop_required": true,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "Emp0009",
            "project_manager": "kgp001",
            "business_lead": "Emp0010",
            "client_executive_lead": "Emp0011",
            "have_laptop": true,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "08/01/2021",
            "expence_estimatedCost": "1400",
            "expence_fromCountry": "India",
            "expence_returnDate": "28/01/2021",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "div944",
            "project": "10003",
            "organization": "ORG150866",
            "emp_code": "div944",
            "first_name": "Divyanshu",
            "last_name": "Admin",
            "details": [
                {
                    "id": 477,
                    "travel_req_id_id": "TR788994",
                    "travelling_country": "India",
                    "travelling_country_to": "United States",
                    "office_location": "100006",
                    "client_number": "",
                    "organization": null,
                    "source_city": "New Delhi",
                    "destination_city": "New York, NY",
                    "departure_date": "2021-01-08T07:19:37.773000Z",
                    "return_date": "2021-01-27T18:30:00Z",
                    "is_accmodation_required": false,
                    "accmodation_start_date": "",
                    "accmodation_end_date": "",
                    "travel_purpose": "Business",
                    "assignment_type": null,
                    "applicable_visa": "Business",
                    "visa_number": "gdfgdfgdf",
                    "visa_expiry_date": "2021-03-10T18:30:00.000Z",
                    "host_hr_name": "errwe",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "34534543543",
                    "is_client_location": false,
                    "client_name": "",
                    "client_address": "",
                    "hotel_cost": 0,
                    "per_diem_cost": 1000,
                    "airfare_cost": null,
                    "transportation_cost": 400,
                    "total_cost": 1400,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": false
                }
            ],
            "dependent": []
        },
        {
            "id": 494,
            "date_created": "2021-01-08T12:28:37.502178+05:30",
            "date_modified": "2021-01-08T12:28:37.502185+05:30",
            "created_by": "Emp112",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR247463",
            "project_name": "3M Lights on support",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": "testing",
            "home_contact_name": "Himanshu",
            "home_phone_ext": "+91",
            "home_phone_number": "8505957287",
            "is_laptop_required": true,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "Emp0009",
            "project_manager": "kgp001",
            "business_lead": "Emp0010",
            "client_executive_lead": "Emp0011",
            "have_laptop": true,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "08/01/2021",
            "expence_estimatedCost": "2280",
            "expence_fromCountry": "United States",
            "expence_returnDate": "28/01/2021",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "Emp112",
            "project": "10002",
            "organization": "ORG150866",
            "emp_code": "Emp112",
            "first_name": "Divyanshu",
            "last_name": "Kumar",
            "details": [
                {
                    "id": 476,
                    "travel_req_id_id": "TR247463",
                    "travelling_country": "United States",
                    "travelling_country_to": "United States",
                    "office_location": "100006",
                    "client_number": "8978545145",
                    "organization": null,
                    "source_city": "New York, NY",
                    "destination_city": "Indianapolis, IN",
                    "departure_date": "2021-01-08T06:52:36.397000Z",
                    "return_date": "2021-01-27T18:30:00Z",
                    "is_accmodation_required": true,
                    "accmodation_start_date": "2021-01-08T06:52:36.397Z",
                    "accmodation_end_date": "2021-01-18T18:30:00.000Z",
                    "travel_purpose": "Work",
                    "assignment_type": null,
                    "applicable_visa": "",
                    "visa_number": "",
                    "visa_expiry_date": "",
                    "host_hr_name": "Himanshu",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "8505957287",
                    "is_client_location": true,
                    "client_name": "Steve",
                    "client_address": "Gurgaon",
                    "hotel_cost": 880,
                    "per_diem_cost": 1000,
                    "airfare_cost": null,
                    "transportation_cost": 400,
                    "total_cost": 2280,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": true
                }
            ],
            "dependent": [
                {
                    "id": 308,
                    "date_created": "2021-01-08T12:28:40.669391+05:30",
                    "date_modified": "2021-01-08T12:28:40.669401+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "SP",
                    "dependent_name": "test9",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR247463",
                    "organization": null
                },
                {
                    "id": 309,
                    "date_created": "2021-01-08T12:28:40.695276+05:30",
                    "date_modified": "2021-01-08T12:28:40.695285+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "PR",
                    "dependent_name": "p1",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR247463",
                    "organization": null
                },
                {
                    "id": 310,
                    "date_created": "2021-01-08T12:28:40.718713+05:30",
                    "date_modified": "2021-01-08T12:28:40.718720+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "Ot",
                    "dependent_name": "test2",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR247463",
                    "organization": null
                }
            ]
        },
        {
            "id": 493,
            "date_created": "2021-01-08T12:01:59.701086+05:30",
            "date_modified": "2021-01-08T12:01:59.701096+05:30",
            "created_by": "div944",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR680724",
            "project_name": "garbage",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": null,
            "home_contact_name": "jhg",
            "home_phone_ext": "+973",
            "home_phone_number": "7567",
            "is_laptop_required": false,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "",
            "project_manager": "",
            "business_lead": "",
            "client_executive_lead": "",
            "have_laptop": false,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "30/12/2020",
            "expence_estimatedCost": "1999",
            "expence_fromCountry": "India",
            "expence_returnDate": "13/01/2021",
            "expence_toCountry": "United Kingdom",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "div944",
            "project": "400002",
            "organization": "ORG150866",
            "emp_code": "div944",
            "first_name": "Divyanshu",
            "last_name": "Admin",
            "details": [
                {
                    "id": 475,
                    "travel_req_id_id": "TR680724",
                    "travelling_country": "India",
                    "travelling_country_to": "United Kingdom",
                    "office_location": "100001",
                    "client_number": "",
                    "organization": null,
                    "source_city": "New Delhi",
                    "destination_city": "Newcastle",
                    "departure_date": "2020-12-29T18:30:00Z",
                    "return_date": "2021-01-12T18:30:00Z",
                    "is_accmodation_required": true,
                    "accmodation_start_date": "2020-12-29T18:30:00.000Z",
                    "accmodation_end_date": "2021-01-11T18:30:00.000Z",
                    "travel_purpose": "Business",
                    "assignment_type": null,
                    "applicable_visa": "",
                    "visa_number": "",
                    "visa_expiry_date": "",
                    "host_hr_name": "hgfh",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "6546",
                    "is_client_location": false,
                    "client_name": "",
                    "client_address": "",
                    "hotel_cost": 845,
                    "per_diem_cost": 560,
                    "airfare_cost": null,
                    "transportation_cost": 140,
                    "total_cost": 1545,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": false
                }
            ],
            "dependent": []
        },
        {
            "id": 492,
            "date_created": "2021-01-07T14:32:36.529287+05:30",
            "date_modified": "2021-01-07T14:32:36.529295+05:30",
            "created_by": "Emp112",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR212853",
            "project_name": "BorgWarner Sales Support",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": true,
            "is_travel_multi_city": true,
            "request_notes": null,
            "remark": null,
            "home_contact_name": "Himanshu",
            "home_phone_ext": "+91",
            "home_phone_number": "8505957287",
            "is_laptop_required": false,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "Emp0009",
            "project_manager": "kgp001",
            "business_lead": "Emp0010",
            "client_executive_lead": "Emp0011",
            "have_laptop": false,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "07/01/2021",
            "expence_estimatedCost": "0",
            "expence_fromCountry": "United States",
            "expence_returnDate": "07/01/2021",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "Emp112",
            "project": "10411",
            "organization": "ORG150866",
            "emp_code": "Emp112",
            "first_name": "Divyanshu",
            "last_name": "Kumar",
            "details": [
                {
                    "id": 473,
                    "travel_req_id_id": "TR212853",
                    "travelling_country": "United States",
                    "travelling_country_to": "India",
                    "office_location": "",
                    "client_number": "",
                    "organization": null,
                    "source_city": "Newark, NJ",
                    "destination_city": "New Delhi",
                    "departure_date": "2021-01-07T09:01:04.601000Z",
                    "return_date": "2021-01-07T09:01:04.601000Z",
                    "is_accmodation_required": false,
                    "accmodation_start_date": "",
                    "accmodation_end_date": "",
                    "travel_purpose": "",
                    "assignment_type": null,
                    "applicable_visa": "",
                    "visa_number": "",
                    "visa_expiry_date": "",
                    "host_hr_name": null,
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": null,
                    "is_client_location": false,
                    "client_name": "",
                    "client_address": "",
                    "hotel_cost": 0,
                    "per_diem_cost": 0,
                    "airfare_cost": null,
                    "transportation_cost": 0,
                    "total_cost": 0,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": false
                },
                {
                    "id": 474,
                    "travel_req_id_id": "TR212853",
                    "travelling_country": "United States",
                    "travelling_country_to": "United States",
                    "office_location": "100006",
                    "client_number": "",
                    "organization": null,
                    "source_city": "New York, NY",
                    "destination_city": "Dallas, TX",
                    "departure_date": "2021-01-07T09:01:04.601000Z",
                    "return_date": "2021-01-07T09:01:04.601000Z",
                    "is_accmodation_required": false,
                    "accmodation_start_date": "",
                    "accmodation_end_date": "",
                    "travel_purpose": "Work",
                    "assignment_type": null,
                    "applicable_visa": "",
                    "visa_number": "",
                    "visa_expiry_date": "",
                    "host_hr_name": "Himanshu",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "85824684",
                    "is_client_location": false,
                    "client_name": "",
                    "client_address": "",
                    "hotel_cost": 0,
                    "per_diem_cost": 0,
                    "airfare_cost": null,
                    "transportation_cost": 0,
                    "total_cost": 0,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": false
                }
            ],
            "dependent": []
        },
        {
            "id": 489,
            "date_created": "2021-01-06T16:24:28.635168+05:30",
            "date_modified": "2021-01-06T16:24:28.635178+05:30",
            "created_by": "div944",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR840727",
            "project_name": "3M - Platform Enhancements",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": "test",
            "home_contact_name": "test",
            "home_phone_ext": "+264",
            "home_phone_number": "657575868678",
            "is_laptop_required": true,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "Emp0009",
            "project_manager": "kgp001",
            "business_lead": "Emp0010",
            "client_executive_lead": "Emp0011",
            "have_laptop": true,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "06/01/2021",
            "expence_estimatedCost": "0",
            "expence_fromCountry": "India",
            "expence_returnDate": "31/01/2021",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "div944",
            "project": "10001",
            "organization": "ORG150866",
            "emp_code": "div944",
            "first_name": "Divyanshu",
            "last_name": "Admin",
            "details": [
                {
                    "id": 470,
                    "travel_req_id_id": "TR840727",
                    "travelling_country": "India",
                    "travelling_country_to": "United States",
                    "office_location": "100006",
                    "client_number": "",
                    "organization": null,
                    "source_city": "New Delhi",
                    "destination_city": "New York, NY",
                    "departure_date": "2021-01-06T10:48:56.451000Z",
                    "return_date": "2021-01-30T18:30:00Z",
                    "is_accmodation_required": false,
                    "accmodation_start_date": "",
                    "accmodation_end_date": "",
                    "travel_purpose": "Work",
                    "assignment_type": null,
                    "applicable_visa": "",
                    "visa_number": "",
                    "visa_expiry_date": "",
                    "host_hr_name": "tet",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "567767888",
                    "is_client_location": false,
                    "client_name": "",
                    "client_address": "",
                    "hotel_cost": 0,
                    "per_diem_cost": 1250,
                    "airfare_cost": null,
                    "transportation_cost": 500,
                    "total_cost": 1750,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": true
                }
            ],
            "dependent": [
                {
                    "id": 305,
                    "date_created": "2021-01-06T16:24:32.780210+05:30",
                    "date_modified": "2021-01-06T16:24:32.780223+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "Parent",
                    "dependent_name": "papa",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR840727",
                    "organization": null
                },
                {
                    "id": 306,
                    "date_created": "2021-01-06T16:24:32.911278+05:30",
                    "date_modified": "2021-01-06T16:24:32.911289+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "Sibling",
                    "dependent_name": "sis",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR840727",
                    "organization": null
                },
                {
                    "id": 307,
                    "date_created": "2021-01-06T16:24:32.936267+05:30",
                    "date_modified": "2021-01-06T16:24:32.936277+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "Other",
                    "dependent_name": "hgjg",
                    "dependent_passport": null,
                    "dependent_visa": null,
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR840727",
                    "organization": null
                }
            ]
        },
        {
            "id": 488,
            "date_created": "2020-12-30T15:53:42.086124+05:30",
            "date_modified": "2020-12-30T15:53:42.086134+05:30",
            "created_by": "div944",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR144292",
            "project_name": "garbage",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": "hgjghj",
            "home_contact_name": "jhjgh",
            "home_phone_ext": "+61",
            "home_phone_number": "56756",
            "is_laptop_required": false,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "",
            "project_manager": "",
            "business_lead": "",
            "client_executive_lead": "",
            "have_laptop": false,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "31/12/2020",
            "expence_estimatedCost": "3570",
            "expence_fromCountry": "India",
            "expence_returnDate": "21/01/2021",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "div944",
            "project": "400002",
            "organization": "ORG150866",
            "emp_code": "div944",
            "first_name": "Divyanshu",
            "last_name": "Admin",
            "details": [
                {
                    "id": 469,
                    "travel_req_id_id": "TR144292",
                    "travelling_country": "India",
                    "travelling_country_to": "United States",
                    "office_location": "100006",
                    "client_number": "",
                    "organization": null,
                    "source_city": "New Delhi",
                    "destination_city": "New Orleans, LA",
                    "departure_date": "2020-12-30T18:30:00Z",
                    "return_date": "2021-01-20T18:30:00Z",
                    "is_accmodation_required": true,
                    "accmodation_start_date": "Thu Dec 31 2020 00:00:00 GMT+0530 (India Standard Time)",
                    "accmodation_end_date": "Wed Jan 20 2021 00:00:00 GMT+0530 (India Standard Time)",
                    "travel_purpose": "Work",
                    "assignment_type": null,
                    "applicable_visa": "",
                    "visa_number": "",
                    "visa_expiry_date": "",
                    "host_hr_name": "hghfg",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "65756",
                    "is_client_location": false,
                    "client_name": "",
                    "client_address": "",
                    "hotel_cost": 1600,
                    "per_diem_cost": 1050,
                    "airfare_cost": 500,
                    "transportation_cost": 420,
                    "total_cost": 3570,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": false
                }
            ],
            "dependent": []
        },
        {
            "id": 487,
            "date_created": "2020-12-30T12:56:42.722510+05:30",
            "date_modified": "2020-12-30T12:56:42.722520+05:30",
            "created_by": "div944",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR282566",
            "project_name": "garbage",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": "dg",
            "home_contact_name": "fgf",
            "home_phone_ext": "+376",
            "home_phone_number": "54",
            "is_laptop_required": false,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "",
            "project_manager": "",
            "business_lead": "",
            "client_executive_lead": "",
            "have_laptop": false,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "30/12/2020",
            "expence_estimatedCost": "0",
            "expence_fromCountry": "India",
            "expence_returnDate": "30/12/2020",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "div944",
            "project": "400002",
            "organization": "ORG150866",
            "emp_code": "div944",
            "first_name": "Divyanshu",
            "last_name": "Admin",
            "details": [],
            "dependent": []
        },
        {
            "id": 484,
            "date_created": "2020-12-29T12:20:52.559055+05:30",
            "date_modified": "2020-12-29T12:20:52.559064+05:30",
            "created_by": "div944",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR253867",
            "project_name": "garbage",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": null,
            "home_contact_name": "jh",
            "home_phone_ext": "+973",
            "home_phone_number": "76",
            "is_laptop_required": false,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "",
            "project_manager": "",
            "business_lead": "",
            "client_executive_lead": "",
            "have_laptop": false,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "30/12/2020",
            "expence_estimatedCost": "906",
            "expence_fromCountry": "India",
            "expence_returnDate": "13/01/2021",
            "expence_toCountry": "United Kingdom",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "div944",
            "project": "400002",
            "organization": "ORG150866",
            "emp_code": "div944",
            "first_name": "Divyanshu",
            "last_name": "Admin",
            "details": [
                {
                    "id": 466,
                    "travel_req_id_id": "TR253867",
                    "travelling_country": "India",
                    "travelling_country_to": "United Kingdom",
                    "office_location": "100001",
                    "client_number": "",
                    "organization": null,
                    "source_city": "New Delhi",
                    "destination_city": "Newcastle",
                    "departure_date": "2020-12-29T18:30:00Z",
                    "return_date": "2021-01-12T18:30:00Z",
                    "is_accmodation_required": false,
                    "accmodation_start_date": "",
                    "accmodation_end_date": "",
                    "travel_purpose": "Business",
                    "assignment_type": null,
                    "applicable_visa": "",
                    "visa_number": "",
                    "visa_expiry_date": "",
                    "host_hr_name": "jh",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "76",
                    "is_client_location": false,
                    "client_name": "",
                    "client_address": "",
                    "hotel_cost": 0,
                    "per_diem_cost": 560,
                    "airfare_cost": null,
                    "transportation_cost": 140,
                    "total_cost": 700,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": false
                }
            ],
            "dependent": []
        },
        {
            "id": 474,
            "date_created": "2020-12-23T17:11:12.077258+05:30",
            "date_modified": "2020-12-23T17:11:12.077269+05:30",
            "created_by": "div944",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR270523",
            "project_name": "garbage",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": null,
            "home_contact_name": "kjhk",
            "home_phone_ext": "+213",
            "home_phone_number": "8678",
            "is_laptop_required": false,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "",
            "project_manager": "",
            "business_lead": "",
            "client_executive_lead": "",
            "have_laptop": false,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "24/12/2020",
            "expence_estimatedCost": "388",
            "expence_fromCountry": "India",
            "expence_returnDate": "30/12/2020",
            "expence_toCountry": "United Kingdom",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "div944",
            "project": "400002",
            "organization": "ORG150866",
            "emp_code": "div944",
            "first_name": "Divyanshu",
            "last_name": "Admin",
            "details": [
                {
                    "id": 456,
                    "travel_req_id_id": "TR270523",
                    "travelling_country": "India",
                    "travelling_country_to": "United Kingdom",
                    "office_location": "100001",
                    "client_number": "",
                    "organization": null,
                    "source_city": "New Delhi",
                    "destination_city": "Newcastle",
                    "departure_date": "2020-12-23T18:30:00Z",
                    "return_date": "2020-12-29T18:30:00Z",
                    "is_accmodation_required": false,
                    "accmodation_start_date": "",
                    "accmodation_end_date": "",
                    "travel_purpose": "Business",
                    "assignment_type": null,
                    "applicable_visa": "",
                    "visa_number": "",
                    "visa_expiry_date": "",
                    "host_hr_name": "khjk",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "7866",
                    "is_client_location": false,
                    "client_name": "",
                    "client_address": "",
                    "hotel_cost": 0,
                    "per_diem_cost": 240,
                    "airfare_cost": null,
                    "transportation_cost": 60,
                    "total_cost": 300,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": false
                }
            ],
            "dependent": []
        },
        {
            "id": 473,
            "date_created": "2020-12-23T16:39:49.949228+05:30",
            "date_modified": "2020-12-23T16:39:49.949238+05:30",
            "created_by": "div944",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR227948",
            "project_name": "3M Sales Support",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": null,
            "home_contact_name": "jghj",
            "home_phone_ext": "+213",
            "home_phone_number": "6757",
            "is_laptop_required": false,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "Emp0009",
            "project_manager": "kgp001",
            "business_lead": "Emp0010",
            "client_executive_lead": "Emp0011",
            "have_laptop": false,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "25/12/2020",
            "expence_estimatedCost": "323",
            "expence_fromCountry": "India",
            "expence_returnDate": "30/12/2020",
            "expence_toCountry": "United Kingdom",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "div944",
            "project": "10003",
            "organization": "ORG150866",
            "emp_code": "div944",
            "first_name": "Divyanshu",
            "last_name": "Admin",
            "details": [],
            "dependent": []
        },
        {
            "id": 472,
            "date_created": "2020-12-23T16:25:42.861312+05:30",
            "date_modified": "2020-12-23T16:25:42.861323+05:30",
            "created_by": "div944",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR149094",
            "project_name": "3M Sales Support",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": null,
            "home_contact_name": "jgh",
            "home_phone_ext": "+376",
            "home_phone_number": "75676",
            "is_laptop_required": false,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "Emp0009",
            "project_manager": "kgp001",
            "business_lead": "Emp0010",
            "client_executive_lead": "Emp0011",
            "have_laptop": false,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "25/12/2020",
            "expence_estimatedCost": "350",
            "expence_fromCountry": "India",
            "expence_returnDate": "30/12/2020",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "div944",
            "project": "10003",
            "organization": "ORG150866",
            "emp_code": "div944",
            "first_name": "Divyanshu",
            "last_name": "Admin",
            "details": [
                {
                    "id": 455,
                    "travel_req_id_id": "TR149094",
                    "travelling_country": "India",
                    "travelling_country_to": "United States",
                    "office_location": "100006",
                    "client_number": "",
                    "organization": null,
                    "source_city": "New Delhi",
                    "destination_city": "Newark, NJ",
                    "departure_date": "2020-12-24T18:30:00Z",
                    "return_date": "2020-12-29T18:30:00Z",
                    "is_accmodation_required": false,
                    "accmodation_start_date": "",
                    "accmodation_end_date": "",
                    "travel_purpose": "Business",
                    "assignment_type": null,
                    "applicable_visa": "Business",
                    "visa_number": "gdfgdfgdf",
                    "visa_expiry_date": "2021-03-10T18:30:00.000Z",
                    "host_hr_name": "jghj",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "765",
                    "is_client_location": false,
                    "client_name": "",
                    "client_address": "",
                    "hotel_cost": 0,
                    "per_diem_cost": 250,
                    "airfare_cost": null,
                    "transportation_cost": 100,
                    "total_cost": 350,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": false
                }
            ],
            "dependent": []
        },
        {
            "id": 471,
            "date_created": "2020-12-23T16:22:42.121045+05:30",
            "date_modified": "2020-12-23T16:22:42.121057+05:30",
            "created_by": "div944",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR150861",
            "project_name": "garbage",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": null,
            "home_contact_name": "hfgh",
            "home_phone_ext": "+43",
            "home_phone_number": "5756",
            "is_laptop_required": false,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "",
            "project_manager": "",
            "business_lead": "",
            "client_executive_lead": "",
            "have_laptop": false,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "25/12/2020",
            "expence_estimatedCost": "350",
            "expence_fromCountry": "India",
            "expence_returnDate": "30/12/2020",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "div944",
            "project": "400002",
            "organization": "ORG150866",
            "emp_code": "div944",
            "first_name": "Divyanshu",
            "last_name": "Admin",
            "details": [
                {
                    "id": 454,
                    "travel_req_id_id": "TR150861",
                    "travelling_country": "India",
                    "travelling_country_to": "United States",
                    "office_location": "100006",
                    "client_number": "",
                    "organization": null,
                    "source_city": "New Delhi",
                    "destination_city": "New York, NY",
                    "departure_date": "2020-12-24T18:30:00Z",
                    "return_date": "2020-12-29T18:30:00Z",
                    "is_accmodation_required": false,
                    "accmodation_start_date": "2020-12-24T18:30:00.000Z",
                    "accmodation_end_date": "",
                    "travel_purpose": "Business",
                    "assignment_type": null,
                    "applicable_visa": "Business",
                    "visa_number": "gdfgdfgdf",
                    "visa_expiry_date": "2021-03-10T18:30:00.000Z",
                    "host_hr_name": "gfdg",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "54654",
                    "is_client_location": false,
                    "client_name": "",
                    "client_address": "",
                    "hotel_cost": 0,
                    "per_diem_cost": 250,
                    "airfare_cost": null,
                    "transportation_cost": 100,
                    "total_cost": 350,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": false
                }
            ],
            "dependent": []
        },
        {
            "id": 460,
            "date_created": "2020-12-17T17:23:59.345935+05:30",
            "date_modified": "2020-12-17T17:23:59.345945+05:30",
            "created_by": "tushaar001",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR301940",
            "project_name": "Project with EA BL CEL",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": "5151",
            "home_contact_name": "ho",
            "home_phone_ext": "+972",
            "home_phone_number": "212616",
            "is_laptop_required": false,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "Emp0009",
            "project_manager": "kgp001",
            "business_lead": "Emp0010",
            "client_executive_lead": "Emp0011",
            "have_laptop": false,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "17/12/2020",
            "expence_estimatedCost": "1640",
            "expence_fromCountry": "India",
            "expence_returnDate": "19/12/2020",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "tushaar001",
            "project": "300004",
            "organization": "ORG150866",
            "emp_code": "tushaar001",
            "first_name": "Tushaar",
            "last_name": "pathak",
            "details": [
                {
                    "id": 444,
                    "travel_req_id_id": "TR301940",
                    "travelling_country": "India",
                    "travelling_country_to": "United States",
                    "office_location": "100006",
                    "client_number": "",
                    "organization": null,
                    "source_city": "New Delhi",
                    "destination_city": "New York, NY",
                    "departure_date": "2020-12-17T11:51:29.470000Z",
                    "return_date": "2020-12-18T18:30:00Z",
                    "is_accmodation_required": false,
                    "accmodation_start_date": "",
                    "accmodation_end_date": "",
                    "travel_purpose": "Work",
                    "assignment_type": null,
                    "applicable_visa": "Work",
                    "visa_number": "work_My_USA_001",
                    "visa_expiry_date": "2020-08-30T18:30:00.000Z",
                    "host_hr_name": "1111",
                    "host_country_head": null,
                    "host_attorney": null,
                    "host_phone_no": "22222",
                    "is_client_location": false,
                    "client_name": "",
                    "client_address": "",
                    "hotel_cost": 0,
                    "per_diem_cost": 100,
                    "airfare_cost": 1500,
                    "transportation_cost": 40,
                    "total_cost": 1640,
                    "travel_request_status": null,
                    "travel_request_status_notes": null,
                    "is_dependent": true
                }
            ],
            "dependent": [
                {
                    "id": 286,
                    "date_created": "2020-12-17T17:24:01.841910+05:30",
                    "date_modified": "2020-12-17T17:24:01.841920+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "Child",
                    "dependent_name": "Child",
                    "dependent_passport": "pass child",
                    "dependent_visa": "work_child_USA_001",
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR301940",
                    "organization": null
                },
                {
                    "id": 287,
                    "date_created": "2020-12-17T17:24:01.877868+05:30",
                    "date_modified": "2020-12-17T17:24:01.877877+05:30",
                    "created_by": "system",
                    "modified_by": "system",
                    "status": false,
                    "req_id": "0",
                    "dependent_relation": "Other",
                    "dependent_name": "kush",
                    "dependent_passport": "pass kush",
                    "dependent_visa": "work_kush_USA_001",
                    "column1": null,
                    "column2": null,
                    "column3": null,
                    "column4": null,
                    "column5": null,
                    "column6": null,
                    "column7": null,
                    "column8": null,
                    "column9": null,
                    "column10": null,
                    "column11": null,
                    "column12": null,
                    "travel_req_id": "TR301940",
                    "organization": null
                }
            ]
        },
        {
            "id": 454,
            "date_created": "2020-12-14T17:45:23.300446+05:30",
            "date_modified": "2020-12-14T17:45:23.300455+05:30",
            "created_by": "div944",
            "modified_by": "system",
            "status": false,
            "travel_req_id": "TR136522",
            "project_name": "garbage1",
            "policy_violations": null,
            "is_billable": true,
            "is_travel_multi_country": false,
            "is_travel_multi_city": false,
            "request_notes": null,
            "remark": "tests",
            "home_contact_name": "test",
            "home_phone_ext": "+355",
            "home_phone_number": "3242424",
            "is_laptop_required": true,
            "travel_req_status": "2",
            "travel_req_status_notes": null,
            "current_ticket_owner": "divyanshuk@triazinesoft.com",
            "supervisor": "Emp112",
            "expense_approver": "",
            "project_manager": "",
            "business_lead": "",
            "client_executive_lead": "",
            "have_laptop": true,
            "approval_level": "0",
            "expence_cureency": "USD",
            "expence_departureDate": "14/12/2020",
            "expence_estimatedCost": "2150",
            "expence_fromCountry": "India",
            "expence_returnDate": "31/12/2020",
            "expence_toCountry": "United States",
            "column1": null,
            "column2": null,
            "column3": null,
            "column4": null,
            "column5": null,
            "column6": null,
            "column7": null,
            "column8": null,
            "column9": null,
            "column10": null,
            "column11": null,
            "column12": null,
            "emp_email": "div944",
            "project": "400001",
            "organization": "ORG150866",
            "emp_code": "div944",
            "first_name": "Divyanshu",
            "last_name": "Admin",
            "details": [],
            "dependent": []
        }
    ]
}
    """;

  ApprovalModal fact;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    String receivedJson = approvalList;
    Map<String, dynamic> list = json.decode(receivedJson);

    fact = ApprovalModal.fromJson(list);
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        iconTheme: IconThemeData(color: Colors.black),
        backgroundColor: Colors.white38,
        elevation: 0,
        title: Text("Approvals",
            style: TextStyle(color: Colors.black, fontSize: 17.0)),
        centerTitle: true,
      ),
      body: Container(
        margin: EdgeInsets.fromLTRB(10, 0, 10, 0),
        child: Column(
          children: [
            Expanded(
              flex: 15,
              child: ListView.builder(
                  shrinkWrap: false,
                  itemCount: fact.data.length,
                  itemBuilder: (BuildContext context, int index) {
                    return GestureDetector(
                        onTap: () {
                          setState(() {
                            fact.data[index].isSelected =
                                !fact.data[index].isSelected;
                          });
                        },
                        child: Cell(fact.data[index]));
                  }),
            ),
            Expanded(
              flex: 2,
              child: Center(
                child: Container(
                  width: MediaQuery.of(context).size.width * 0.95,
                  height: 40,
                  child: FlatButton(
                    child: Text(
                      'SELECT',
                      style: TextStyle(fontSize: 20.0),
                      textAlign: TextAlign.center,
                    ),
                     textColor: Colors.white,
                    color: AppConstants.APP_THEME_COLOR,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    onPressed: () {
                      Navigator.pushNamed(context, '/Dashboard');
                    },
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class Cell extends StatefulWidget {
  Data fact;
  Function(bool) changeValue;

  Cell(this.fact, {this.changeValue});

  @override
  _CellState createState() => _CellState();
}

class _CellState extends State<Cell> {
  bool myvalue;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.fromLTRB(0, 10, 0, 0),
      child: Column(
        children: [
          Row(
            children: <Widget>[
              Expanded(
                flex: 6,
                child: Column(
                  children: [
                    TextWidget(
                        "Employee Name", 13.0, null, Colors.black54, 2.0),
                    TextWidget(widget.fact.firstName + widget.fact.lastName,
                        15.0, FontWeight.w700, null, 7.0),
                    Row(
                      children: [
                        Expanded(
                          flex: 3,
                          child: Column(
                            children: [
                              TextWidget(
                                  "From Date", 13.0, null, Colors.black54, 4.0),
                              TextWidget(widget.fact.expenceDepartureDate, 13.0,
                                  FontWeight.w600, null, 0),
                            ],
                          ),
                        ),
                        Expanded(
                          flex: 4,
                          child: Column(
                            children: [
                              TextWidget(
                                  "To Date", 13.0, null, Colors.black54, 4.0),
                              TextWidget(widget.fact.expenceReturnDate, 13.0,
                                  FontWeight.w600, null, 0),
                            ],
                          ),
                        )
                      ],
                    ),
                  ],
                ),
              ),
              Expanded(
                flex: 4,
                child: Container(
                  padding: EdgeInsets.fromLTRB(5, 0, 0, 0),
                  child: Column(
                    children: [
                      TextWidget(
                          "Travel Request ID", 13.0, null, Colors.black54, 2.0),
                      TextWidget(widget.fact.travelReqId, 16.0, FontWeight.w700,
                          AppConstants.APP_THEME_COLOR, 7.0),
                      TextWidget(
                          "Employee ID", 13.0, null, Colors.black54, 2.0),
                      TextWidget(widget.fact.empCode, 15.0, FontWeight.w600,
                          Colors.black, 0),
                    ],
                  ),
                ),
              ),
              Expanded(
                flex: 1,
                child: Checkbox(
                  checkColor: Colors.white,
                  activeColor: AppConstants.APP_THEME_COLOR,
                  value: widget.fact.isSelected,
                  onChanged: (bool value) {
                    this.setState(() {
                      widget.fact.isSelected = !widget.fact.isSelected;
                    });
                    widget.changeValue(value);
                  },
                ),
              ),
            ],
          ),
          SizedBox(height: 10),
          Container(
            height: 1,
            color: Colors.black38,
          ),
        ],
      ),
    );
  }
}

class TextWidget extends StatelessWidget {
  TextWidget(this.value, this.fontSize, this.fontWeight, this.fontColor,
      this.paddingBottom);

  final String value;
  final double fontSize;
  final FontWeight fontWeight;
  final dynamic fontColor;
  final double paddingBottom;

  //final double padding;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.fromLTRB(0, 0, 0, paddingBottom),
      child: Align(
        alignment: Alignment.centerLeft,
        child: Text(
          value,
          style: TextStyle(
              fontSize: fontSize, color: fontColor, fontWeight: fontWeight),
        ),
      ),
    );
  }
}
